vimpager : update + customisation invocation (suppression mappings 				   less-like, résout le bug de C-])

diff --git a/bin/vimpager b/bin/vimpager
--- a/bin/vimpager
+++ b/bin/vimpager
@@ -2,7 +2,7 @@
 
 # Script for using ViM as a PAGER.
 # Based on Bram's less.sh.
-# Version 1.7.5
+# Version 1.8.2
 # git://github.com/rkitover/vimpager.git
 
 # Just pass through if not on a tty
@@ -17,25 +17,38 @@ case $(uname -s) in
 	CYGWIN*) cygwin=1 ;;
 	MINGW*) msys=1 ;;
 	OpenBSD) openbsd=1; bsd=1 ;;
+	FreeBSD) freebsd=1; bsd=1 ;;
+	NetBSD) netbsd=1; bsd=1 ;;
 	*) bsd=1 ;;
 esac
+
+# grep -q is often not available
+grep_q() {
+	_pat=$1
+	shift
+	awk '
+		BEGIN { exit_val = 1 }
+		$0 ~ /'"$_pat"'/ { exit_val = 0; exit(exit_val) }
+		END { exit(exit_val) }
+	' "$@"
+}
 
 # Use the real TEMP directory on windows in case we are using a native vim/gvim
 tmp=/tmp
 [ -n "${msys}" -o -n "${cygwin}" ] && tmp=$(printf "%s\n" "${TEMP}" | tr '\\' /)
 
 # Detect terminal size
-if command -v tput > /dev/null; then
+if command -v tput >/dev/null; then
 	# this is the only way it works on Cygwin
-	trap "rm -f /tmp/vimpager_cols_${$} /tmp/vimpager_lines_${$}" HUP INT QUIT ILL TRAP KILL BUS TERM
+	trap "rm -f '${tmp}/vimpager_cols_${$}' '${tmp}/vimpager_lines_${$}'" HUP INT QUIT ILL TRAP KILL BUS TERM
 
-	tput cols  > /tmp/vimpager_cols_${$}
-	tput lines > /tmp/vimpager_lines_${$}
+	tput cols  > "${tmp}/vimpager_cols_${$}"
+	tput lines > "${tmp}/vimpager_lines_${$}"
 
-	cols=$(cat /tmp/vimpager_cols_${$})
-	lines=$(cat /tmp/vimpager_lines_${$})
+	cols=$(cat "${tmp}/vimpager_cols_${$}")
+	lines=$(cat "${tmp}/vimpager_lines_${$}")
 
-	rm -f /tmp/vimpager_cols_${$} /tmp/vimpager_lines_${$}
+	rm -f "${tmp}/vimpager_cols_${$}" "${tmp}/vimpager_lines_${$}"
 fi
 
 # msys has no tput, this doesn't work on Cygwin by the way
@@ -52,32 +65,74 @@ if [ -z "${cols}" ]; then
 	no_pass_thru=1 # force loading vimpager
 fi
 
-# determine location of vimrc
+find_vim_dir() {
+	trap "rm -f '${tmp}/vimpager_vim_dir_${$}'" HUP INT QUIT ILL TRAP KILL BUS TERM
+
+	vim -E -c 'call writefile([ $VIM ], "'${tmp}'/vimpager_vim_dir_'${$}'") | q' </dev/null
+	vim_dir=$(head -1 "${tmp}/vimpager_vim_dir_${$}")
+
+	rm -f "${tmp}/vimpager_vim_dir_${$}"
+}
+
+# this uses the heuristics described in :help startup
+find_rc() {
+	_cmd=$1
+	_rc_file=$2
+
+	[ -e "${HOME}/.${_rc_file}" ] && _rc="${HOME}/.${_rc_file}"
+
+	if [ -n "${msys}" -o -n "${cygwin}" ]; then
+		if command -v ${_cmd} 2>/dev/null | grep_q '^\/(cygdrive\/)?[a-z]\/'; then
+			eval "win32_native_${cmd}=1"
+
+			if [ -e "${HOME}/_${_rc_file}" ]; then
+				_rc="${HOME}/_${_rc_file}"
+			elif [ -z "${_rc}" ]; then
+				[ -z "${vim_dir}" ] && find_vim_dir
+
+				if [ -e "${vim_dir}/_${_rc_file}" ]; then
+					_rc="${vim_dir}/_${_rc_file}"
+				elif [ -e "${vim_dir}/.${_rc_file}" ]; then
+					_rc="${vim_dir}/.${_rc_file}"
+				fi
+			fi
+		fi
+	fi
+
+	echo "${_rc}"
+
+	unset _cmd _rc_file _rc
+}
+
+# determine location of rc file
+
+# first check for a user ~/.vimpagerrc
 if [ -n "${VIMPAGER_RC}" ]; then
-	vimrc=${VIMPAGER_RC}
+	vimrc="${VIMPAGER_RC}"
 elif [ -f ~/.vimpagerrc ]; then
 	vimrc=~/.vimpagerrc
 elif [ -f ~/_vimpagerrc ]; then
 	vimrc=~/_vimpagerrc
-elif [ -f /etc/vimpagerrc ]; then
-	vimrc=/etc/vimpagerrc
 fi
 
+# then check if the user has a ~/.vimrc
+[ -z "${vimrc}" ] && vimrc="$(find_rc vim vimrc)"
+
+# then check for a global /etc/vimpagerrc and fall back to NORC
 if [ -z "${vimrc}" ]; then
-	trap "rm -f ${tmp}/vimpager_vimrc_${$}" HUP INT QUIT ILL TRAP KILL BUS TERM
-
-	vim -E -c 'call writefile([ $MYVIMRC ], "'${tmp}'/vimpager_vimrc_'${$}'") | q' </dev/tty
-	vimrc=$(head -1 ${tmp}/vimpager_vimrc_${$})
-
-	rm -f ${tmp}/vimpager_vimrc_${$}
+	if [ -f /usr/local/etc/vimpagerrc ]; then
+		vimrc=/usr/local/etc/vimpagerrc
+	elif [ -f /etc/vimpagerrc ]; then
+		vimrc=/etc/vimpagerrc
+	else
+		vimrc=NORC
+	fi
 fi
-
-[ -z "${vimrc}" ] && vimrc=NORC
 
 # read settings
-trap "rm -f ${tmp}/vimpager_opts_${$}" HUP INT QUIT ILL TRAP KILL BUS TERM
+trap "rm -f '${tmp}/vimpager_opts_${$}'" HUP INT QUIT ILL TRAP KILL BUS TERM
 
-vim -u ${vimrc} -E --cmd 'set nocp' -c '
+vim -u "${vimrc}" -E --cmd 'set nocp' -c '
 	if !exists("vimpager_use_gvim")
 		let vimpager_use_gvim=0
 	endif
@@ -94,18 +149,18 @@ vim -u ${vimrc} -E --cmd 'set nocp' -c '
 		let vimpager_passthrough=0
 	endif
 
-	call writefile([ vimpager_use_gvim, vimpager_disable_x11, vimpager_scrolloff, vimpager_passthrough, $VIM ], "'${tmp}'/vimpager_opts_'${$}'")
+	call writefile([ vimpager_use_gvim, vimpager_disable_x11, vimpager_scrolloff, vimpager_passthrough ], "'${tmp}'/vimpager_opts_'${$}'")
 	
 	quit
-' </dev/tty
+' </dev/null
 
-[ "$(head -1 < ${tmp}/vimpager_opts_${$})" = 1 ] && use_gvim=1
+[ "$(head -1 < "${tmp}/vimpager_opts_${$}")" = 1 ] && use_gvim=1
 
-[ "$(head -2 < ${tmp}/vimpager_opts_${$} | tail -1)" = 1 ] && disable_x11=1
+[ "$(head -2 < "${tmp}/vimpager_opts_${$}" | tail -1)" = 1 ] && disable_x11=1
 
-scrolloff=$(head -3 < ${tmp}/vimpager_opts_${$} | tail -1)
+scrolloff=$(head -3 < "${tmp}/vimpager_opts_${$}" | tail -1)
 
-[ "$(head -4 < ${tmp}/vimpager_opts_${$} | tail -1)" = 0 ] && no_pass_thru=1
+[ "$(head -4 < "${tmp}/vimpager_opts_${$}" | tail -1)" = 0 ] && no_pass_thru=1
 
 if [ "${no_pass_thru}" = 0 ]; then
 	# check if arithmetic expansion works, passthrough mode relies on it
@@ -114,16 +169,14 @@ if [ "${no_pass_thru}" = 0 ]; then
 	fi
 fi
 
-vim_dir=$(head -5 < ${tmp}/vimpager_opts_${$} | tail -1)
-
-rm -f ${tmp}/vimpager_opts_${$}
+rm -f "${tmp}/vimpager_opts_${$}"
 
 if [ -n "${msys}" -o -n "${cygwin}" ]; then
 	# msys/cygwin may be using a native vim, and if we're not in a real
 	# console the native vim will not work, so we have to use gvim.
 
 	if [ "x${TERM}" != "xdumb" -a "x${TERM}" != "xcygwin" -a "x${TERM}" != "x" ]; then
-		if command -v vim 2>/dev/null | awk '$1 ~ /^\/(cygdrive\/)?[a-z]\// {t=1} END {exit 1-t}'; then
+		if command -v vim 2>/dev/null | grep_q '^\/(cygdrive\/)?[a-z]\/'; then
 			use_gvim=1
 		fi
 	fi
@@ -131,23 +184,7 @@ fi
 
 if [ -n "${use_gvim}" ]; then
 	# find the .gvimrc
-	[ -e ${HOME}/.gvimrc ] && gvimrc=${HOME}/.gvimrc
-
-	if [ -n "${msys}" -o -n "${cygwin}" ]; then
-		if command -v gvim 2>/dev/null | awk '$1 ~ /^\/(cygdrive\/)?[a-z]\// {t=1} END {exit 1-t}'; then
-			win32_native_gvim=1
-
-			if [ -e ${HOME}/_gvimrc ]; then
-				gvimrc=${HOME}/_gvimrc
-			elif [ -z "${gvimrc}" ]; then
-				if [ -e "${vim_dir}/_gvimrc" ]; then
-					gvimrc=${vim_dir}/_gvimrc
-				elif [ -e "${vim_dir}/.gvimrc" ]; then
-					gvimrc=${vim_dir}/.gvimrc
-				fi
-			fi
-		fi
-	fi
+	gvimrc="$(find_rc gvim gvimrc)"
 
 	# determine if this is an ssh session and/or $DISPLAY is set
 	if [ -n "${osx}" ]; then
@@ -201,11 +238,16 @@ less_vim() {
 				vim_cmd="${vim_cmd} -X"
 			fi
 
+			#${vim_cmd} \
+				#-u "${vimrc}" \
+				#--cmd 'let vimpager=1 | runtime! macros/less.vim | set nocp' \
+				#-c "set scrolloff=${scrolloff:-5} | set foldlevel=999 | set nonu | silent! set nornu |
+					#nmap <ESC>u :nohlsearch<cr> | noremap q :<C-u>q<CR> | nnoremap <Down> 1<C-d> | nnoremap <Up> 1<C-u>" \
+				#"${@:--}"
 			${vim_cmd} \
-				-u ${vimrc} \
-				--cmd 'let vimpager=1 | runtime! macros/less.vim | set nocp' \
-				-c "set scrolloff=${scrolloff:-5} | set foldlevel=999 | set nonu | silent! set nornu |
-				    nmap <ESC>u :nohlsearch<cr> | noremap q :q<CR> | nnoremap <Down> 1<C-d> | nnoremap <Up> 1<C-u>" \
+				-u "${vimrc}" \
+				--cmd 'set nocp' \
+				-c "set scrolloff=${scrolloff:-5} | set foldlevel=999 | set nonu | silent! set nornu" \
 				"${@:--}"
 			;;
 		*) # gvim or mvim GUI
@@ -214,7 +256,7 @@ less_vim() {
 			# Check if the user maximized the window in ~/_gvimrc on Win32, if
 			# so restore on startup.
 			if [ -n "${gvimrc}" -a \( -n "${cygwin}" -o -n "${msys}" \) ]; then
-				simalt=$(grep simalt ${gvimrc} 2>/dev/null | head -1)
+				simalt=$(grep simalt "${gvimrc}" 2>/dev/null | head -1)
 
 				if [ -n "${simalt}" ]; then
 					restore="simalt ~r"
@@ -222,16 +264,34 @@ less_vim() {
 			fi
 
 			${vim_cmd} \
-				-u ${vimrc} \
+				-u "${vimrc}" \
 				--cmd 'let vimpager=1 | runtime! macros/less.vim | set nocp' \
 				-c "set scrolloff=${scrolloff:-5} | set foldlevel=999 | set nonu | silent! set nornu |
-				    nmap <ESC>u :nohlsearch<cr> | noremap q :q<CR> | nnoremap <Down> 1<C-d> | nnoremap <Up> 1<C-u> |
+				    nmap <ESC>u :nohlsearch<cr> | noremap q :<C-u>q<CR> | nnoremap <Down> 1<C-d> | nnoremap <Up> 1<C-u> |
 				    ${colors:-echo} | ${restore:-echo} | set lines=${lines} | set columns=${cols}" \
 				"${@:--}" &
 			;;
 	esac
 
 	rm -f gvim.exe.stackdump # for cygwin gvim, which can be part of vim
+}
+
+awk_pstree_freebsd() {
+	awk -v mypid=${1} '{
+		cmd[$1]=$3
+		ppid[$1]=$2
+		arg[$1]=$4
+	}
+	END {
+		while (mypid != 1 && cmd[mypid]) {
+			if (cmd[mypid] == "/bin/sh" && arg[mypid] == "/usr/bin/man")
+				ptree=mypid " /usr/bin/man\n" ptree
+			else
+				ptree=mypid " " cmd[mypid] "\n" ptree
+			mypid=ppid[mypid]
+		}
+		print ptree
+	}'
 }
 
 awk_pstree() {
@@ -248,7 +308,7 @@ awk_pstree() {
 	}'
 }
 
-do_ptree() {
+_do_ptree() {
 	if [ -n "${solaris}" ]; then
 		# Tested on Solaris 8 and 10
 		ptree ${$}
@@ -256,22 +316,31 @@ do_ptree() {
 		ps | awk '{ print $1 "\t" $2 "\t" $NF }' | awk_pstree ${$}
 	elif [ -n "${openbsd}" ]; then
 		ps awo pid=,ppid=,command= | awk_pstree ${$}
+	elif [ -n "${freebsd}" ]; then
+		ps aw -o pid= -o ppid= -o command= | awk_pstree_freebsd ${$}
+	elif [ -n "${netbsd}" ]; then
+		ps aw -o pid= -o ppid= -o command= | awk_pstree ${$}
 	else
 		# Tested on Linux and OS X
 		ps awo pid=,ppid=,comm= | awk_pstree ${$}
 	fi
 }
 
+# silence warnings about DY* variables on OSX
+do_ptree() {
+	_do_ptree "$@" 2>/dev/null
+}
+
 # Check if called from man, perldoc or pydoc
-if do_ptree | awk '$2 ~ /(^|\/)(man|perl(doc)?([0-9.]*)?|py(thon|doc|doc2))/ {t=1} END { exit 1-t }'; then
-	extra_c="set ft=man"
+if do_ptree | grep_q '(^|\/)(man|perl(doc)?([0-9.]*)?|py(thon|doc|doc2))'; then
+	extra_c='set ft=man'
 fi
 
 extra_cmd="let vimpager_ptree=[$(do_ptree | awk '{ print "\"" $2 "\"" }' | tr '\n' ',')] | call remove(vimpager_ptree, -1)"
 
-trap "rm -rf ${tmp}/vimpager_${$}" HUP INT QUIT ILL TRAP KILL BUS TERM
+trap "rm -rf '${tmp}/vimpager_${$}'" HUP INT QUIT ILL TRAP KILL BUS TERM
 
-mkdir -m 0700 ${tmp}/vimpager_${$}
+mkdir -m 0700 "${tmp}/vimpager_${$}"
 
 command -v perl > /dev/null && \
 	perl -le 'exit($] >= 5.008001 ? 0 : 1)' && have_perl=1
@@ -279,9 +348,9 @@ command -v perl > /dev/null && \
 # Normally, filter outputs ANSI-escape-code-free content to STDERR.
 # When content is short, filter outputs content with ANSI escape codes to STDOUT.
 filter() {
+	OLDIFS="${IFS}"
 	if [ -z "${no_pass_thru}" ]; then
 		content=
-		OLDIFS="${IFS}"
 		# ts: tab stop
 		# nl: number of physycal lines
 		# dh: display height
@@ -326,6 +395,26 @@ filter() {
 	fi
 }
 
+# Check for certain parameters to pass on to vim (or conceivably do something else)
+# Currently only checks for "+G" as in less which will start reading the file
+# at the end. Also supports just "+" as in vim.
+# Couldn't use getopt or getopts as neither supports options prepended with +
+checkAndProcessParameter() {
+    case "$1" in
+        "+G" | "+")
+               vim_cmd="${vim_cmd} +"
+               ;;
+        *)
+               return 1
+               ;;
+    esac
+    return 0
+}
+
+while checkAndProcessParameter $1; do
+    shift
+done
+
 filename=${@:-stdin}
 filename=$(echo "${filename}" | tr '/' '_')
 filename="${tmp}/vimpager_${$}/${filename}"
@@ -352,6 +441,11 @@ case $(echo "${@}" | tr 'A-Z' 'a-z') in
 		;;
 esac
 
+# dumb man detection when the pstree heuristic fails
+if head -6 "${filename}" | grep_q '^NAME$'; then
+	extra_c='set ft=man'
+fi
+
 # if file is zero length, or one blank line (cygwin) exit immediately
 if [ \( ! -s "${filename}" \) \
 	-o \( \( "$(cat "${filename}")" = "" \) \
@@ -373,13 +467,34 @@ less_vim -c "${extra_c:-echo}" --cmd "${extra_cmd:-echo}" "${filename}" </dev/tt
 # On Win32 we must also wait for the process to exit before the file can
 # be deleted.
 (
-	while [ -d ${tmp}/vimpager_${$} ]; do
-		sleep 10
-		rm -rf ${tmp}/vimpager_${$} 2>/dev/null
+	while [ -d "${tmp}/vimpager_${$}" ]; do
+		sleep 10 
+		rm -rf "${tmp}/vimpager_${$}" 2>/dev/null
 		rm -f gvim.exe.stackdump 2>/dev/null
 	done
 ) &
 
+# Copyright (c) 2013, Rafael Kitover
+#
+# Redistribution and use in source and binary forms, with or without
+# modification, are permitted provided that the following conditions are met:
+# * Redistributions of source code must retain the above copyright
+# notice, this list of conditions and the following disclaimer.
+# * Redistributions in binary form must reproduce the above copyright
+# notice, this list of conditions and the following disclaimer in the
+# documentation and/or other materials provided with the distribution.
+#
+# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER ``AS IS'' AND ANY
+# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
+# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
+# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
+# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
+# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
+# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
+# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
+# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
+# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+#
 # CONTRIBUTORS:
 #
 # Rafael Kitover
@@ -399,5 +514,9 @@ less_vim -c "${extra_c:-echo}" --cmd "${extra_cmd:-echo}" "${filename}" </dev/tt
 # Simon Olofsson <simon@olofsson.de>
 # lickel: Adam Lickel <adam@lickel.com>
 # eworm-de: Christian Hesse <mail@eworm.de>
+# krijesta: Chris Chambers <krijesta@google.com>
+# vincer: vince rosso <vince@locationlabs.com>
+# justinkb: Paul Mulders <justinkb@gmail.com>
+# nonakap: NONAKA Kimihiro <nonakap@gmail.com>
 
 # vim:noet ts=8 sts=8 sw=8 tw=0:
